### ISSUE TITLE
есть вопросы по созданию автотестов

### ISSUE THREAD

**Issue by aksiaaksi** [aksiaaksi/tele2#1]
Создал автотесты и закомментировал их прошу проверить

**Comment by coursar** [comment]
Логика должна быть следующая:
1. Добавляете, допустим, 4 тарифа (2 актуальных, 2 архивированных)
1. Просите актуальные - смотрите, что именно те, которые вы положили
1. Просите архивные - смотрите, что именно те, которые вы положили
